version: '3'

services:
  database-product:
    container_name: database_product
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    volumes:
      - database-product:/var/lib/postgresql/data
  database-warehouse:
    container_name: database_warehouse
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
    volumes:
      - database-warehouse:/var/lib/postgresql/data
  module-config:
    container_name: module-config
    build:
      context: ./module-config
      dockerfile: Dockerfile
    restart: always
    environment: 
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://module-eureka:8080/eureka
        SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/var/module-config/configuration
    volumes:
      - ./configuration:/var/module-config/configuration
  module-eureka:
    container_name: module-eureka
    build:
      context: ./module-eureka
      dockerfile: Dockerfile
    restart: always
    environment: 
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://module-eureka:8080/eureka
    ports:
      - 8090:8080
  module-ng:
    container_name: module-ng
    build:
      context: ./module-ng
      dockerfile: Dockerfile
    restart: always
    environment: 
        API_URL: http://module-gateway:8080/api
    ports:
      - 8087:80
  module-gateway:
    container_name: module-gateway
    build:
      context: ./module-gateway
      dockerfile: Dockerfile
    restart: always
    environment: 
        SPRING_CONFIG_IMPORT: configserver:http://module-config:8080
        MODULE_GATEWAY_HOST: module-gateway:8080
  module-product-1:
    container_name: module-product-1
    build:
      context: ./module-product
      dockerfile: Dockerfile
    restart: always
    environment: 
        EUREKA_INSTANCE_INSTANCE_ID: 1
        SPRING_CONFIG_IMPORT: configserver:http://module-config:8080
  module-product-2:
    container_name: module-product-2
    build:
      context: ./module-product
      dockerfile: Dockerfile
    restart: always
    environment: 
        EUREKA_INSTANCE_INSTANCE_ID: 2
        SPRING_CONFIG_IMPORT: configserver:http://module-config:8080
  module-warehouse:
    container_name: module-warehouse
    build:
      context: ./module-warehouse
      dockerfile: Dockerfile
    environment: 
        SPRING_CONFIG_IMPORT: configserver:http://module-config:8080
    restart: always
volumes:
  database-product:
  database-warehouse: