### Get All Products
GET http://localhost:8081/api/products

### Get Product by Id
GET http://localhost:8081/api/products/87daf4f4-7fca-4b76-8f93-2ced3252131e

### Get Products by Warehouse Id
GET http://localhost:8081/api/warehouses/123e4567-e89b-12d3-a456-426614174000/products

### Create Product
POST http://localhost:8081/api/products
Content-Type: application/json

{
  "name": "iPhone 12",
  "weight": 5,
  "warehouseId": "123e4567-e89b-12d3-a456-426614174000"
}

### Create Product (bad request)
POST http://localhost:8081/api/products
Content-Type: application/json

{
  "name": "iPhone 12",
  "weight": 5,
  "warehouseId": "00000000-0000-0000-0000-000000000000"
}

### Update Product
PUT http://localhost:8081/api/products/951e7530-951e-951e-951e-951e7530951e
Content-Type: application/json

{
  "name": "smartphone",
  "weight": 15,
  "warehouseId": "044e3210-9bca-32d1-ba56-499602026999"
}

### Delete Product
DELETE http://localhost:8081/api/products/951e7530-951e-951e-951e-951e7530951e

### Create Warehouse
POST http://localhost:8081/api/warehouses
Content-Type: application/json

{
  "id": "123e4567-e89b-12d3-a456-426614174123"
}

### Delete Warehouse
DELETE http://localhost:8081/api/warehouses/123e4567-e89b-12d3-a456-426614174000
